ladivic: include/ldvc_mem.hpp File Reference
ldvc_mem.hpp File Reference
Memory management utilities for dynamic allocation and deallocation.
#include <cstddef>
#include <mutex>
#include <ldvc_type.hpp>
Functions
template<typename T >
T * ldvc_malloc (usize size)
Allocates memory for an array of elements.
template<typename T >
void ldvc_free (T *object)
Deallocates memory previously allocated by ldvc_malloc or similar functions.
template<typename T >
T * ldvc_realloc (T *ptr, usize size)
Reallocates memory for an array of elements.
template<typename T >
T * ldvc_calloc (usize num)
Allocates and initializes memory for an array of elements.
Variables
std::mutex ldvc_mem_mutx
Mutex for thread-safe memory management.
Detailed Description
Memory management utilities for dynamic allocation and deallocation.
This header file provides functions for dynamic memory allocation and deallocation, including allocation, reallocation, and deallocation of memory blocks. Thread safety is ensured during these operations using a mutex.
Author
Nathanne Isip
Definition in file ldvc_mem.hpp.
Function Documentation
ldvc_calloc()
template<typename T > T * ldvc_calloc (usize num)
Allocates and initializes memory for an array of elements.
This function allocates memory for an array of elements of type T with the specified size and initializes all elements to zero.
Template Parameters
T The type of elements to allocate memory for.
Parameters
num The number of elements to allocate memory for.
Returns
A pointer to the allocated memory block, or nullptr if allocation fails.
Definition at line 133 of file ldvc_mem.hpp.
{
    T* ptr = ldvc_malloc<T>(num);
    if(ptr != nullptr)
        for (size_t i = 0; i < num; ++i)
            ptr[i] = T();
    return ptr;
}
ldvc_free()
template<typename T > void ldvc_free (T * object)
Deallocates memory previously allocated by ldvc_malloc or similar functions.
This function deallocates memory previously allocated by ldvc_malloc or similar functions.
Template Parameters
T The type of elements in the memory block to deallocate.
Parameters
object A pointer to the memory block to deallocate.
Definition at line 84 of file ldvc_mem.hpp.
{
    const std::lock_guard<std::mutex> lock(ldvc_mem_mutx);
    ::operator delete(object);
}
Referenced by ldvc_realloc().
ldvc_malloc()
template<typename T > T * ldvc_malloc (usize size)
Allocates memory for an array of elements.
This function allocates memory for an array of elements of type T with the specified size.
Template Parameters
T The type of elements to allocate memory for.
Parameters
size The number of elements to allocate memory for.
Returns
A pointer to the allocated memory block, or nullptr if allocation fails.
Definition at line 61 of file ldvc_mem.hpp.
{
    const std::lock_guard<std::mutex> lock(ldvc_mem_mutx);
    T* ptr = static_cast<T*>(::operator new(size * sizeof(T)));
    if(ptr == nullptr)
        return (int*) -1;
    return ptr;
}
Referenced by ldvc_calloc(), and ldvc_realloc().
ldvc_realloc()
template<typename T > T * ldvc_realloc (T * ptr, usize size)
Reallocates memory for an array of elements.
This function reallocates memory for an array of elements of type T with the specified size.
Template Parameters
T The type of elements to reallocate memory for.
Parameters
ptr A pointer to the memory block to reallocate.
size The new number of elements to allocate memory for.
Returns
A pointer to the reallocated memory block, or nullptr if reallocation fails.
Definition at line 106 of file ldvc_mem.hpp.
{
    T* new_ptr = ldvc_malloc<T>(size);
    if(ptr != nullptr) {
        for (size_t i = 0; i < size; ++i)
            new_ptr[i] = ptr[i];
        ldvc_free(ptr);
    }
    return new_ptr;
}
Variable Documentation
ldvc_mem_mutx
std::mutex ldvc_mem_mutx
Mutex for thread-safe memory management.
Definition at line 44 of file ldvc_mem.hpp.
Referenced by ldvc_free(), and ldvc_malloc().